main: cloud.swiftnode.kspam.KSpam
name: K-Spam_Community_Edition
version: @version@
author: EntryPoint
commands:
  kspam:
    description: K-SPAM main command.
    usage: /kspam
  kspamerror:
    description: Off the error message and display the error players.
    usage: /kspamerror
  kspamcheck:
    description: Shows whether this IP is blocked or not.
    usage: /kspamcheck IP/Player
  kspamforce:
    description: ForceMode on/off.
    usage: /kspamforce
  kspamrem:
    description: Remove an ip in cached data.
    usage: /kspamrem IP